package com.github.mati1979.play.hysterix;

public enum HysterixEventType {

    SUCCESS, FAILURE, TIMEOUT, FALLBACK_SUCCESS, FALLBACK_FAILURE, RESPONSE_FROM_CACHE, SHORT_CIRCUITED, EXCEPTION_THROWN

}
